simulation:
  base_case: "cylinder2D"

io:
  fo_name: "dataToSmartRedis"
experiment:
  name: "cylinder2D-svd"
  exp_path: "run/cylinder2D-svd"
  launcher: "local"

svd_params:
  num_mpi_ranks: 4
  svd_rank: 40
  batch_size: 1000
  snapshot_sampling_interval: 10
  end_time: 3000
  start_index: 1000

database_settings:
  db_port: 6780
  interface: "lo"

delete_snapshot_batch: False

plot:
  compare_direct_partitioned: True #needs "delete_snapshot_batch" == False
  CTU_factor: 10

ref:
  p_ref: 1
  u_ref: 1
