simulation:
  base_case: "cylinder2D"

io:
  fo_name: "dataToSmartRedis"
experiment:
  name: "cylinder2D-svd"
  exp_path: "run/cylinder2D-svd"
  launcher: "local"

svd_params:
  num_mpi_ranks: 4
  svd_rank: 15
  batch_size: 500
  snapshot_sampling_interval: 10
  end_time: 4000

database_settings:
  db_port: 6780
  interface: "lo"
